fixed clicks for single choice tree
oarepo/oarepo-vocabularies pull request #167
Opened 2024-06-06 10:08 UTC by AlbinaMakisheva

2024-06-07 14:12 UTC, mirekys requested changes
![Screenshot 2024-06-07 at 16 11 48](https://github.com/oarepo/oarepo-vocabularies/assets/646743/b9d0f771-fd43-4c8f-b81e-137a440af8b1)

Confirm button has no use here (other than that it just produces an error when clicked), remove it

2024-06-07 14:30 UTC, mirekys commented
![Screenshot 2024-06-07 at 16 30 36](https://github.com/oarepo/oarepo-vocabularies/assets/646743/3453f1f2-ba7f-443d-aa56-f5db8b78b134)
Padding bettween checkbox & text dissapeared

2024-06-10 11:26 UTC, mirekys requested changes

2024-06-10 11:26 UTC, mirekys commented on oarepo_vocabularies/ui/theme/assets/semantic-ui/js/oarepo_vocabularies_ui/form/components/VocabularyTreeSelectField/TreeSelectFieldModal.jsx
>                  <Button
Semantically wrong element, shouldn't be a button, this is a List.Item & only button this list item should contain is the ">" to open children column. Correct DOM should look like (not exact, you can possibly use List.Content, List.Icon or List.Header inside as per SUI docs):

```
<List.Item>
  <Checkbox /> // if multiple
  {option.hierarchy.title[0]}
  <Button> // if parent node
    <Icon name="angle right" color="black" />
  </Button>
</List.Item>
```

2024-06-10 11:26 UTC, mirekys commented on oarepo_vocabularies/ui/theme/assets/semantic-ui/js/oarepo_vocabularies_ui/form/components/VocabularyTreeSelectField/TreeSelectFieldModal.jsx
>                  <Button
Using the correct elements would be much easier to do, than to convince buttons to look like list items and don't break the other buttons appearance at the same time ;)

2024-06-11 10:41 UTC, mirekys requested changes

2024-06-11 10:41 UTC, mirekys commented on oarepo_vocabularies/ui/theme/assets/semantic-ui/js/oarepo_vocabularies_ui/form/components/VocabularyTreeSelectField/TreeSelectFieldModal.jsx
> +  useEffect(() => {
Can we do it without resorting to useEffect? When in multiselect mode, this effect is completely unnecessarily registered & evaluated everytime someone selects something...

2024-06-11 10:41 UTC, mirekys commented on oarepo_vocabularies/ui/theme/assets/semantic-ui/js/oarepo_vocabularies_ui/form/components/VocabularyTreeSelectField/TreeSelectFieldModal.jsx
> +      </ModalContent>{" "}
Why is this space here?

2024-06-17 11:46 UTC, Ducica commented
@AlbinaMakisheva @mirekys May I please ask for another modification, where the TreeSelect will accept also a prop, that is a function and that will enable to make filtering of all options based on some condition, similar like it is in https://github.com/oarepo/oarepo-vocabularies/blob/bfbd29028d77c623774d06f036897477c2c4a424/oarepo_vocabularies/ui/theme/assets/semantic-ui/js/oarepo_vocabularies_ui/form/components/LocalVocabularySelectField/LocalVocabularySelectField.jsx#L102 filterFunction prop. The reason is that some fields, for example, resource type, we need to have different options depending if they are located in the main form, or in the relatedItems field. Thanks!

2024-06-17 13:59 UTC, mirekys commented
> @AlbinaMakisheva @mirekys May I please ask for another modification, where the TreeSelect will accept also a prop, that is a function and that will enable to make filtering of all options based on some condition, similar like it is in
> 
> https://github.com/oarepo/oarepo-vocabularies/blob/bfbd29028d77c623774d06f036897477c2c4a424/oarepo_vocabularies/ui/theme/assets/semantic-ui/js/oarepo_vocabularies_ui/form/components/LocalVocabularySelectField/LocalVocabularySelectField.jsx#L102
> 
> filterFunction prop. The reason is that some fields, for example, resource type, we need to have different options depending if they are located in the main form, or in the relatedItems field. Thanks!

Yes this `filterFunction` prop is needed also for restoration repo for pre-filtering of options based on object's primary material. E.g. if object is from "sklo", then all the `restorationMethods` also needs to be prefiltered by that. Isn't the functionality already somewhere there @AlbinaMakisheva ?

2024-06-19 15:27 UTC, mirekys requested changes
Clicking on parent selects nothing:
https://github.com/oarepo/oarepo-vocabularies/assets/646743/65e90bde-9e19-4450-b68c-44b20a03f215

Additionally theres no pointer cursor indicating that item is clickable, theres no hover state

2024-06-19 15:31 UTC, mirekys reviewed
On mobile it is impossible to see 3rd level of tree (missing horizontal scroll container if modal content overflows screen)
<img width="599" alt="Screenshot 2024-06-19 at 17 30 00" src="https://github.com/oarepo/oarepo-vocabularies/assets/646743/d8e8f02d-9626-49cf-8585-cfb52c79b503">

2024-06-19 15:35 UTC, mirekys requested changes
Currently selected value not reflected by modal (it should be highlighted as selected)
https://github.com/oarepo/oarepo-vocabularies/assets/646743/85ef41e4-bc97-4f4e-9d7a-c46338915e74

or checkboxes checked in multi-selection mode:

https://github.com/oarepo/oarepo-vocabularies/assets/646743/2c285365-681b-4532-b2a8-5529f25e2704

2024-06-28 08:04 UTC, mirekys commented
> Clicking on parent selects nothing: https://github.com/oarepo/oarepo-vocabularies/assets/646743/65e90bde-9e19-4450-b68c-44b20a03f215
> 
> Additionally theres no pointer cursor indicating that item is clickable, theres no hover state

Still no pointer cursor to indicate clickability, i get `I` cursor when hovering over an item

2024-06-28 09:01 UTC, mirekys commented
> Currently selected value not reflected by modal (it should be highlighted as selected) https://github.com/oarepo/oarepo-vocabularies/assets/646743/85ef41e4-bc97-4f4e-9d7a-c46338915e74

In single-value mode, currently selected value is still not shown/distinguished from others when modal opens

2024-07-01 17:54 UTC, mirekys approved these changes

2024-07-01 18:02 UTC, merged